website/food/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'food'
urlpatterns = [
    # Path food/ from urls.py on website project
    #path('', views.index, name='index'), #Replaced to use class views
    path('', views.IndexClassView.as_view(), name='index'),
    #path('item/', views.item, name='item'),
    #path('<int:item_id>/', views.detail, name='detail'),
    path('<int:pk>/', views.FoodDetail.as_view(), name='detail'),
    # Add items
    #path('add', views.create_item, name="create_item"),
    path('add', views.CreateItem.as_view(), name="create_item"),
    # Update items
    path('update/<int:id>/', views.update_item, name="update_item"),
    # Delete
    path('delete/<int:id>/', views.delete_item, name="delete_item"),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name = 'user/login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name = 'user/logout.html'), name='logout'),
    path('profile/', user_views.profilepage, name='profile'),
]



urlpatterns += [
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Item(models.Model):

    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="http://www.ukvisitorguide.cn/wp-content/uploads/2015/11/Food-placeholder.jpg")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})

website/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

website/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']
        

website/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields =['username','email','password1','password2']

website/food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView


# Create your views here.
def index(request):
    item_list = Item.objects.all()
    template = loader.get_template('food/index.html')
    context = {
        'item_list': item_list,
    }
    return render(request,'food/index.html', context)


class IndexClassView(ListView):
    model = Item;
    template_name = 'food/index.html'
    context_object_name = 'item_list'

class FoodDetail(DetailView):
    model = Item;
    template_name = 'food/item.html'

class CreateItem(CreateView):
    model = Item;
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)
    
    template_name = 'food/item-form.html'

def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item-form.html', {'form': form, 'item': item})


def delete_item(request, id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    return render(request, 'food/item.html', {'item': item})


'''


def item(request):
    return HttpResponse('This is an item view')

def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item': item,
    }
    template = loader.get_template('food/item.html')
    return render(request,'food/item.html', context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/item-form.html', {'form': form})


'''

website/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"Your account is created")
            return redirect('login') # return redirect('food:index')
    else:
        form = RegisterForm()
    return render(request, 'user/register.html', {'form': form})

@login_required
def profilepage(request):

    return render(request, 'user/profile.html')

website/food/templates/food/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>FoodApp</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    
  </head>
  <body>
    {% include 'food/navbar.html' %}
    <div class="container">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-warning alert-dismissible fade show mt-4" role="alert">
            <p>{{ message }}</p>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>  
        {% endfor %}
      {% endif %}
      {% block content %}
      {% endblock %}
    </div>

        <!-- Footer -->
        <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
          <symbol id="bootstrap" viewBox="0 0 118 94">
            <title>FoodApp</title>
            <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
          </symbol>
          <symbol id="facebook" viewBox="0 0 16 16">
            <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"></path>
          </symbol>
          <symbol id="instagram" viewBox="0 0 16 16">
              <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"></path>
          </symbol>
          <symbol id="twitter" viewBox="0 0 16 16">
            <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"></path>
          </symbol>
        </svg>
      <div class="container">
          <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <div class="col-md-4 d-flex align-items-center">
              <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
                <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
              </a>
              <span class="mb-3 mb-md-0 text-body-secondary">© 2023 Erick Vivas</span>
            </div>
        
            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
              <li class="ms-3"><a class="text-body-secondary" href="https://twitter.com/erickvivas"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
              <li class="ms-3"><a class="text-body-secondary" href="https://github.com/erickvivas415"><svg width="24" height="24" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                  <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
                </svg></a></li>
              </ul>
          </footer>
        </div>
        <!-- End Footer -->
    


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

  </script>
  </body>
</html>

website/food/templates/food/index.html
{% extends 'food/base.html' %}

{% block content %}

    {% for item in item_list %}
    <div class="row m-2">
        <div class="col-md-3 offset-md-2">
            <img class="img-thumbnail" height="50px" src="{{ item.item_image }}" alt="">
            
        </div>
        <div class="col-md-4">
            <h3>{{item.item_name}}</a></h3>
            <h5>{{ item.item_desc }}</h5>
            <h6>$ {{ item.item_price }}</h6>
        </div>
        <div class="col-md-2">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-secondary">Details</a>
        </div>
    </div>
    {% endfor %}

{% endblock %}

website/food/templates/food/item-form.html
{% extends 'food/base.html' %}

{% block content %}

    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <button class="btn btn-secondary" type="submit">Save</button>
    </form>


{% endblock %}

website/food/templates/food/item.html
{% extends 'food/base.html' %}

{% block content %}

<div class="card mt-4" style="width: 18rem;">
    <img src="{{item.item_image}}" class="card-img-top" alt="...">
    <div class="card-body">      
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><h5 class="card-title">{{ object.item_name }}</h5></li>
        <li class="list-group-item"><p class="card-text">{{ object.item_desc }}</p></li>
        <li class="list-group-item"><p class="card-text">$ {{ object.item_price }}</p></li>
      </ul>
      <a href="{% url 'food:update_item' item.id %}" class="btn btn-primary mb-2" >Update</a>
      <form method="POST" action="{% url 'food:delete_item' item.id %}">
        {% csrf_token %}
        <button class="btn btn-primary mb-2" type="submit">Delete</button>
      </form>
      <a href="{% url 'food:index' %}" class="btn btn-primary" >Go back</a>
    </div>
</div>

{% endblock %}

website/food/templates/food/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'food:index' %}">FoodApp</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'food:create_item' %}">Add Item</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Delete Item</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">View Item</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'profile' %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

website/users/templates/user/login.html
{% extends 'food/base.html' %}

{% block content %}
<div class="col-md-3 offset-md-3 mt-3">
    <div class="card">
        <div class="card-header">
            Login
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {% for field in form%}
                    <div class="form-group m-2">
                        {{ field.name }}
                        {{ field }}
                    </div>
                {% endfor %}
                
                <button class="btn btn-secondary" type="submit">Log In</button>
            </form>
        </div>
    </div>
    

</div>

{% endblock %}

website/users/templates/user/logout.html
{% extends 'food/base.html' %}

{% block content %}
<div class="col-md-6 offset-md-3 mt-3">

    <h1>You have been logged out</h1>

</div>

{% endblock %}

website/users/templates/user/profile.html
{% extends 'food/base.html' %}

{% block content %}
<div class="col-md-6 offset-md-3 mt-3">

    <div class="card" style="width: 18rem;">
        <img src="{{ user.profile.image.url }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{ user.username }}</h5>
          <p class="card-text">{{ user.profile.location }}</p>
          <a width="100px" href="{% url 'food:index' %}" class="btn btn-primary">Go back</a>
        </div>
      </div>


</div>

{% endblock %}

website/users/templates/user/register.html
{% extends 'food/base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-dark">
                    <div class="card-title">
                        Register
                    </div>
                    <div class="card-body">
                        <form class="mt-4" method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    <p class="text-uppercase">{{ field.name }}</p>
                                    <p>{{ field }}</p>
                                </div>
                            {% endfor %}
                            <button class="btn btn-secondary" type="submit">Sign Up</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}